### ISSUE TITLE
Animations with non-linear arranged tiles

### ISSUE THREAD

**Issue by feendrache** [Kiamo2/YATI#1]
**Is your feature request related to a problem? Please describe.**
This request points to this thing mentioned in the readme:

> Tileset animation in Godot requires involved tiles being equidistant and either horizontally or vertically arranged.
> 
> In Tiled you can randomly choose every frame tile, such animations won't map and are skipped.

**Describe the solution you'd like**
in my importer i found a solution for this:
https://github.com/feendrache/Godot4-TiledImporter
in https://github.com/feendrache/Godot4-TiledImporter/blob/main/naddys_tiled_maps/tileset_creator.gd
around line 143 i made a function to get the tiles used by the animation

**Additional context**
I created my importer due to need and would stop working on it, redirecting the people to you if this would be ok

**Comment by Kiamo2** [comment]
Hi, first of all: yes of course it's ok to redirect.
Looking on your code around line 143 I see it deals with the separation value.
Separation is calculated by YATI, maybe "equidistant" is not the right wording.
I meant you can have e.g. tiles 1,2,3,4 or 1,3,5,7 or 1,4,7,10 and so on, but not 1,3,4,8,15...
So I'm not sure if I could improve anything unless Godot allows individual separation for each frame.
Or do I missunderstand this?

**Comment by feendrache** [comment]
Yeah you're right there is only the single sparation.. had some other things in my mind... but it seams like mixing is not working... i have so much stuff on my mind it simply registered: i had a solution for animations not being directly next to each other... 

So i will make a test with your importer soon and then post a redirect in my repo

**Comment by Kiamo2** [comment]
Experimenting in Godot I found that only horizontal and vertical are working, horizontal by column=0 and x value of the separation and vertical by column=1 and y value of the separation. If horizontal (column=0) y has no influence and vice versa.
