### ISSUE TITLE
Installation via AssetLib not working out of the box

### ISSUE THREAD

**Issue by winston-yallow** [Kiamo2/YATI#10]
**Describe the bug**
The folder structure with both the GDScript an CSharp versions in separate subfolders does not work well with the expected structure from godot. To actually use the addon, the user has to move the addon path.

**To Reproduce**
1. Install via asset lib.

**Expected behavior**
It should just work out of the box.

**Proposed Solution**
Either just explain this in the description on the asset lib so that users know this, or adjust the folder structure to work out of the box.
I think the easiest would be to split this into two addons:
```
addons/
    YATI_gdscript/
        plugin.cfg (name: YATI GDScript)
        ...other files
    YATI_csharp/
        plugin.cfg (name: YATI CSharp)
        ...other files
```
This way users can easily download and enable the version they want to have.

**Comment by Kiamo2** [comment]
You're right, the offered download (this button is not supressable) via asset lib really is missleading.
As I don't think that much people would bother with installing both versions, I've added an hopefully simple enough installation recommendation to the description.
Thank you for the hint.
