### ISSUE TITLE
Support sub rects

### ISSUE THREAD

**Issue by dogboydog** [Kiamo2/YATI#12]
**Is your feature request related to a problem? Please describe.**
In Tiled, you can make each tile only use a certain area of an image rather than using the whole image. 

It looks like this in the Tiled UI 

![image](https://github.com/Kiamo2/YATI/assets/9920963/ccb9867e-4101-4132-999e-2033691dff4b)

Which lets you draw a map like this
![image](https://github.com/Kiamo2/YATI/assets/9920963/cf64a70e-90cd-4096-a52d-5c3991c428c4)

But when imported via  YATI, it looks like this in Godot 
![image](https://github.com/Kiamo2/YATI/assets/9920963/80981494-6e5f-42fe-a0a9-7e2b07b5ad30)

**Describe the solution you'd like**
Use an atlas texture or similar in Godot to support this Tiled workflow

**Describe alternatives you've considered**
You could  use some of the other styles of tilesets but this is good for using a single texture

**Additional context**

[subrect_yati.zip](https://github.com/Kiamo2/YATI/files/11780127/subrect_yati.zip)

**Comment by Kiamo2** [comment]
Interesting Tiled feature I'd not yet recognized.
