### ISSUE TITLE
Boolean custom data layers' values are not correctly imported.

### ISSUE THREAD

**Issue by wickworks** [Kiamo2/YATI#13]
**Describe the bug**
When a .tsx tileset has tiles which contain custom boolean properties, those values aren't correctly imported as custom data layers, i.e. anything marked "true" will come through as false.

This is because `TilesetCreator.gd` -> `handle_tile_properties`, doesn't convert `val` to the appropriate type before calling `set_custom_data(name, val)`, so it will try to set a boolean to the string "true" which fails silently and leaves the value as false.

**To Reproduce**
1. Make a tileset that has a tile with a custom bool property set to true
2. Import a map using that tileset
3. Open the tileset in the editor and look at that custom data layer
4. See that it is not marked as true. 

**Expected behavior**
I expect the boolean data to come through just like how ints and strings are working.

**Screenshots**
N/a

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 12.6.6 (21G646)
 - Godot Version v4.0.3.stable.mono.official [5222a99f5]
 - Tiled Version 1.10.1

**Examle map (zipped)**
I can provide one if the above information isn't clear enough.

**Additional context**
Here's my example hack that I've added immediately before the aforementioned `current_tile.set_custom_data(name, val)` to fix the problem for bools specifically. I don't know if colors are working, but I assume that floats are working along with ints and strings.
`if _tileset.get_custom_data_layer_type(custom_layer) == TYPE_BOOL: val = (val.to_lower() == 'true')`

Additionally, there's a [soon-to-be-fixed bug in Godot](https://github.com/godotengine/godot/issues/78485) that can mess up what custom data layer name corresponds to what data due to the addition/removal of the internal `CUSTOM_DATA_INTERNAL` data layer during the import process, which may complicate testing until it's closed.

**Comment by Kiamo2** [comment]
Not only custom data were affected but also meta data.
Thanks for detecting this!
Fixed in v1.3.1
