### ISSUE TITLE
Wang Tilesets / Terrains not correctly imported

### ISSUE THREAD

**Issue by feendrache** [Kiamo2/YATI#14]
**Describe the bug**
Wang Tilesets are not correctly imported, the importer only supports one color for terrains and wangs. 
Not all Tiled Terrains are available in Godot with this import routine

**To Reproduce**
1. Create a more complex Wang Tileset in Tiled
2. Create a map with it
3. Import to godot
4. try to use the terrain

**Expected behavior**
Import all the colors used in the tileset and create all the terrain options needed to use

**Additional context**
i had this working in my discontinued tiled importer, trying to get this working in yati

**Comment by Kiamo2** [comment]
Ok, I will have to take a closer look at this.
Admittedly, I have neglected these "colors" so far, in the cases I have encountered so far there was always only one color in play. In Tiled this is called "terrain", but it is somehow different from the terrain in Godot.
To me it seemed to make the most sense to map Tiled's terrain sets to Godot terrains.
However, this may need to be questioned. One problem that would come up with a change here is that Godot's terrain sets can't be named, they are just automatically numbered ('Terrain Set 0' etc). I'm also not sure if one could work with the result in Godot in a meaningful way (i.e. continue painting).

**Comment by feendrache** [comment]
i will test out the new godot exporter from tiled itself.. since this is really only really needed when you want to use the tileset itself in godot ... this may be the better way

**Comment by feendrache** [comment]
for the maps itself i really prefer YATI, btw...

**Comment by Kiamo2** [comment]
Changed the mapping now in version 1.4.0.
Wangsets are mapped to Godot terrain sets. Names possibly get lost (exception below)
Colors are mapped to Godot terrains. Color name -> Terrain name.
Exception: If no color name is present, the wangset name is used.
The previous/old mapping can be enforced by a new option ('Map Wangset to Terrain').
