### ISSUE TITLE
Animations and some tiles not imported

### ISSUE THREAD

**Issue by BMontens** [Kiamo2/YATI#15]
**Describe the bug**
I made a map in Tiled, but the Godot map is not the same, some props are missing and some animations too.

**To Reproduce**
1. I used "https://rafaelmatos.itch.io/epic-rpg-world-pack-grass-land20-asset", which has Tiled support
2. I made a simple map with water and a wood panel
3. I exported my map and launched Godot

**Expected behavior**
The map should've been imported as in Tiled.

**Screenshots**
[Missing Atlas for props (even though it is in my Godot directory)](https://imgur.com/a/nRMv9Fa)

**Desktop (please complete the following information):**
 - OS: Pops os 22.04
 - Version 1.3.1 (Also in 1.4)
 - Godot Version 4.1.1
 - Tiled Version 1.9.2

**Comment by Kiamo2** [comment]
The .png is searched by the importer where it's reference entry inside the .tsx points to.
Please check the reference entry for the .png file in the .tsx.
It's probably wrong.
The .tsx is a text file and can be edited, the references are easy to find as they are usually at the start of the file.

The warnings are coming from animated tiles which cannot be made animated in Godot 4 (Godot 4 limit).

**Comment by BMontens** [comment]
The tsx has the correct reference.

**Comment by Kiamo2** [comment]
There must be a hidden reason that the file is expected at that place.
Maybe the .tsx with the correct reference is not the actually used .tsx.
Please check all references from top to bottom beginning with the .tmx.
Something in the whole bunch of files and dir paths and references inside the Godot project must be wrong.

Unfortunately I'm unable to be of more help on finding the problem without access to/having this project.

**Comment by Kiamo2** [comment]
There must be a hidden reason that the file is expected at that place.
Maybe the .tsx with the correct reference is not the actually used .tsx.
Please check all references from top to bottom beginning with the .tmx.
Something in the whole bunch of files and dir paths and references inside the Godot project must be wrong.

Unfortunately I'm unable to be of more help on finding the problem without access to/having this project.
