### ISSUE TITLE
Runtime Loading

### ISSUE THREAD

**Issue by jeffgamedev** [Kiamo2/YATI#16]
**Is your feature request related to a problem? Please describe.**
It is possible using the core features in this codebase to load Tiled maps at runtime and not just in-editor. This provides a lot of value.

**Describe the solution you'd like**
I have achieved this feature by taking the code from this repository, removing the requirement of Godot editor, and simply returning a Node2D without saving to resources. Given a clean refactor, this functionality could be extended to both runtime loading and editor. It should be noted that I wrote the alternate runtime version in C#.

**Describe alternatives you've considered**
If runtime loading is not supported, I will continue having a fork and adapt it to your repository's future changes. However I would rather give back to the community and reference this repo directory.

**Additional context**
Let me know if you need access to the c# runtime version.

**Comment by jeffgamedev** [comment]
If you would like to see this feature developed, I can attempt to implement it in C# if that would be helpful.

**Comment by Kiamo2** [comment]
Yes, I'd like to see this feature developed and some real world example.

Sometimes I need some time to fully grasp something.
And in this case it's the "value" or use case. As far as I'm oriented, time resources play a big role in games. So why would anyone want to waste them at runtime on conversions or translations that could be done up front?
And I'm also worried about subsequent requests that might arise e.g. "optimize your code for runtime, it's here or there too slow"...

**Comment by jeffgamedev** [comment]
> some real world example.

The application I am working on aims to allow users to import assets at runtime such as PNG for sprites, OGG for sounds and music, and for this use case Tiled TMX/TMJ files in order for them to easily modify the game. Speaking with other game developers, they find the feature to be attractive for "hot reloading" sort of features.

> Yes, I'd like to see this feature developed

Great! I'll work on a PR in the next few days. I'll retain all the existing functionality, so it will be up to the end user if they wish to even utilize it. It will mostly involve separating out responsibility to different functions.

**Comment by Kiamo2** [comment]
Would that also work in GDScript?

**Comment by jeffgamedev** [comment]
> Would that also work in GDScript?

I don't know, but I imagine it would. I haven't taken a look at the GDScript implementation.

**Comment by Kiamo2** [comment]
May I nevertheless see your current C# runtime implementation like you proposed in your initial issue description?

**Comment by jeffgamedev** [comment]
> Owner

Sure! I just pushed a branch here: https://github.com/jeffgamedev/YATI/tree/runtime-only-c-sharp

You can find it in the /CSharp/runtime/ directory.

**Comment by Kiamo2** [comment]
Hmm, I see the only file which is significantly changed is Importer.cs.
If that's all what's necessary it's probably easiest if I simply with every update create an additional runtime package and offer it for download.
Probably no need for you to further develop, could even be "overkill".
I'd also offer a GDScript version.

**Comment by jeffgamedev** [comment]
> Hmm, I see the only file which is significantly changed is Importer.cs. If that's all what's necessary it's probably easiest if I simply with every update create an additional runtime package and offer it for download. Probably no need for you to further develop, could even be "overkill". I'd also offer a GDScript version.

That's great! Thank you!

**Comment by Kiamo2** [comment]
Runtime packages are now available with v1.5.2

**Comment by jeffgamedev** [comment]
> Runtime packages are now available with v1.5.2

Awesome! Thank you!
