### ISSUE TITLE
Different sized Tilesets in one Map

### ISSUE THREAD

**Issue by feendrache** [Kiamo2/YATI#2]
**Describe the bug**
I have a Map with tilesets with different tilesizes (16x16 and 64x64)
this won't import correctly

**Comment by Kiamo2** [comment]
I've built an testcase for this and it looks that tiles of the 2nd tileset are displaced.
Is this also what you observed?

**Comment by Kiamo2** [comment]
Never mind. For the simpler case that the tilesize of the different sized tileset is exactly factor 2 or 4 bigger I've a solution already in mind but I want to look into what happens if the sizes are completely odd and be sure to find an always stable solution.
Probably need a bit time for this.

**Comment by feendrache** [comment]
just as a hint:
if you set texture_region_size in the atlas source to the main-tile size  and the tilesize in the off-size tilset also it solves the problem.
This tileset then can only be used in maps with the set base-tilesize

**Comment by Kiamo2** [comment]
Thanks for the hint.
But I'm a bit worried about "This tileset then can only be used in maps with the set base-tilesize".
This could later turn out as annoying.

**Comment by feendrache** [comment]
yeah it works in my importert since the tilesets are created for each imported map as i found out.
So Godot imports the tileset tsx files but in the imported tmx the tilesets are also imported separately and the imported separate tsx are NOT used in the map itself

**Comment by Kiamo2** [comment]
Have pre-released a new version 1.1.0, could you please check if it's resolves the issue for you?
You can find it under Releases + 1 release

**Comment by feendrache** [comment]
Tested the new version.
The offset now seems right.
I cannot remember but didn't you use the tilemap layers in the version before? 
Why don't u use the tilemap layers inside godot?

**Comment by Kiamo2** [comment]
I didn't touch the tilemap layers.
To use Godot's tilemap layers is an option ("Use Tilemap Layers"). Maybe you switched it off?

**Comment by feendrache** [comment]
Ahh... switched them off.. wasn't aware of the options

**Comment by feendrache** [comment]
it's off by default

**Comment by Kiamo2** [comment]
I'd like to close the issue and also the other one.
That ok for you?

**Comment by feendrache** [comment]
Yeah, that is ok
