### ISSUE TITLE
Custom Tile data is confusing

### ISSUE THREAD

**Issue by JoelCreatesGames** [Kiamo2/YATI#21]
### Is your feature request related to a problem? Please describe.
This may be partially a nuance of how custom tile data is implemented in Godot, but I think there is room for some documentation improvements here. 

The custom data on the tile is an array of values, which at first made me think there was a bug in the importer for not keeping the key name. I later realized that the custom data keys/types are stored on the tileset themselves.

This is fine that its implemented this way, but can be confusing for a newer user, especially because it combines them from all tiles (meaning the index is global, not the same as the order in Tiled)

The other part that is slightly confusing is the Tiled tileset is where the custom tile data gets stored (where everything else in this plugin is seemingly stored in the map files). This file does not appear in the godot FileSystem dock (when saved there), which may cause confusion about needing the file, embedding it in the map file, etc.

### Describe the solution you'd like
Documentation improvements to help understand:
- how/where custom tile data is stored
- the need for tileset files (.tsx) and embed vs not embed

### Screenshots

![image](https://github.com/Kiamo2/YATI/assets/62071362/51c28128-ea66-4da2-966a-b035c39c52b5)

![image](https://github.com/Kiamo2/YATI/assets/62071362/56b43f0f-1039-4508-820a-8c2e4c81746c)

![image](https://github.com/Kiamo2/YATI/assets/62071362/686a1dce-a2f3-44a7-9076-6dff13baa852)

![image](https://github.com/Kiamo2/YATI/assets/62071362/440e1bfd-c183-40f0-bc99-2e908e1edffe)

**Comment by Kiamo2** [comment]
Have updated the docu and hope it's a bit clearer then.

**Comment by Kiamo2** [comment]
Since no further comments were made, the issue appears resolved.
