### ISSUE TITLE
I can't get to tile animations to animate

### ISSUE THREAD

**Issue by Psygnomi** [Kiamo2/YATI#24]
MacOS Sonoma, Godot 4.1.

I'm new to Godot, so still finding my way - is there a node I need to add to enable tile anims? Couldn't find any mention of tile anims, other than they're supported.

Thanks!

**Comment by Kiamo2** [comment]
You don't need a node or the like, just create animated tiles in Tiled.
BUT: Godot 4 supports tile animation only in horizontal (left to right) and vertical (top to bottom) direction. And the tiles must be equidistant meaning e.g. tile 1, 2, 3, 4... or tile 1, 3, 5, 7,... or 1, 4, 7, 10, ... hope you get the principle.
If the animated tiles in Tiled meet this limiting requirements, upon import they are automatically generated as animated tiles in Godot. If not a warning (in yellow) is put out.
