### ISSUE TITLE
godot_node_type and/or res_path are not loaded from property types file.

### ISSUE THREAD

**Issue by al0fdf** [Kiamo2/YATI#26]
**Describe the bug**
`godot_node_type` and/or `res_path` are not loaded from property types file, as a result, any objects with the relevant properties set, do not get instanced:

**To Reproduce**
1. Create a new class in Tiled's 'Custom Type Editor' with `res_path` and `godot_node_type='instance'` properties.
2. Inside a map file, create an object with `class` property set to above class.
3. Import map in game
4. Objects stay as static bodies instead of becoming scene instances

**To work around**
Double-click the `res_path` and `godot_node_type` for **every** object in the map, change them to non-default values, then change them to their default values, so they become un-greyed.

**Expected behavior**
Objects with `godot_node_type='instance'` and `res_path` set to a .`tscn` file should be instanced in-game.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 1.6.0, gdscript release
 - Godot Version 4.1.2 stable
 - Tiled Version 1.10.2

**Examle map (zipped)**
A zip file containing a small but complete example to reproduce the issue.
This could accelerate resolving it.

**Additional context**

**Comment by Kiamo2** [comment]
Can't reproduce this, it works in my tests.
Could you please zip and append a mini example?

**Comment by erniel** [comment]
@al0fdf try exporting the tmx file instead of just saving it

**Comment by Kiamo2** [comment]
@al0fdf : I've tested now different relative paths and that worked too.
So currently without an example of yours I've no clue.

**Comment by al0fdf** [comment]
@Kiamo2 Here's my reproduction project with the following structure:

```
.
├── addons
│   └── YATI
│       ├── CustomTypes.gd
│       ├── DictionaryBuilder.gd
│       ├── DictionaryFromXml.gd
│       ├── Importer.gd
│       ├── plugin.cfg
│       ├── PostProcessing.gd
│       ├── TiledImport.gd
│       ├── TilemapCreator.gd
│       ├── TilesetCreator.gd
│       └── XmlParserCtrl.gd
├── icon.svg
├── icon.svg.import
├── main.gd
├── main.tscn
├── project.godot
├── test_object.tscn
└── tiled
    ├── map.tmx
    ├── map.tmx.import
    ├── map_working.tmx
    ├── map_working.tmx.import
    ├── propertytypes.json
    ├── repro.tiled-project
    └── tileset.tsx
```

The issue is likely due to relative paths, but I can't figure out the cause.
[yati_repro_project.zip](https://github.com/Kiamo2/YATI/files/13113328/yati_repro_project.zip)

**Comment by Kiamo2** [comment]
Now it's going to be mysterious.
After setting the project file in the import options for map.tmx (was missing there), everything worked well on my side.

Maybe it's indeed Linux behaving different...?
If so it's going to be a bit difficult for me,
-> I'll try to examine the path building and look for potential weaknesses here.

**Comment by al0fdf** [comment]
> Can't find anything and as the res_path entries in 'map_working.tmx' and 'repro.tiled-project' are identical it's no big surprise that it's working. But - as you've written "When running in-game...", are you talking about the runtime version?

I'm talking about running it from the editor.

**Comment by Kiamo2** [comment]
Aah, you've changed the example zip.
OK, I've tested with the changed example and it also works *as soon as I specified the project file in the Project File option*.

Could it be that you simply missed to specify the project file???

Please note, that for Custom Types to be supported the project file is neccessary!
(TBD: Point out that more precise in the docu)
The reason is that Tiled stores its Custom Types in the project file, NOT in the .tmx.
The .tmx only contains the class name.
Unless you overwrite a custom property (not grayed out in Tiled), then it's contained in the .tmx thus the left icon works without project file.

**Comment by al0fdf** [comment]
@Kiamo2L I *have* set the project file in the import defaults:

![image](https://github.com/Kiamo2/YATI/assets/104121665/0d246ca9-a1cc-47c9-8c6d-7526e685c5b3)

However when creating a new inherited scene based on `map.tmx` in the editor, I get:
```
Import file 'res://tiled/map.tmx'
 -- Unknown class 'test_object'. -> Assuming Default
Import finished with 1 warning.
```

When finding that line(around line `652` in `TilemapCreator.gd`), and debug-printing the `_ct` variable, I find that it is `null`, which could explain why the `test_object` class is unknown at that time.

```diff
	if _ct != null:
		_ct.merge_custom_properties(obj, "object")
+	print(_ct)
	
	...
	
	if godot_type == _godot_type.UNKNOWN:
		if not _add_class_as_metadata and class_string != "" and not godot_node_type_prop_found:
			print_rich("[color=" + WARNING_COLOR +"] -- Unknown class '" + class_string + "'. -> Assuming Default[/color]")
			_warning_count += 1
		
		...
```

Godot's console output of the above code:
```
Import file 'res://tiled/map.tmx'
<null>
 -- Unknown class 'test_object'. -> Assuming Default
<null>
Import finished with 1 warning.
```

**Comment by Kiamo2** [comment]
_ct being null is indicating that no project file has been loaded.

You may have set it in the importer defaults, but after I loaded your example, the actual Tiled Project File option for map.tmx was empty.
I had explicitly to set it.
Please check if it is set by looking at the import options when the file 'map.tmx' is selected in the file system window on the left.
(Godot pecularity: If the Import options are empty, select another file and then select 'map.tmx again')

**Comment by al0fdf** [comment]
@Kiamo2 That seems to be the issue. The importer tab does not use the project's default import options. After re-importing the `.tmx` with the project file set in `map.tmx`'s import options, *both* scenes were correctly instanced.

**Comment by Kiamo2** [comment]
I took a closer look and found out:
- The importer defaults only come into play if no (previous) import has been done for a .tmx, i.e. - no .tmx.import file exists parallel to the .tmx yet.
- After an import, the import options used are saved in the .tmx.import file and then have priority over any changed importer defaults.

I think, this explains the behavior and I consider the issue as resolved.
