### ISSUE TITLE
Godot 4.2 - `TileMap.CellQuadrantSize` got renamed 

### ISSUE THREAD

**Issue by fdrobidoux** [Kiamo2/YATI#27]
Simply put, since Godot 4.2, `TileMap.CellQuadrantSize` was renamed to `TileMap.RenderingQuadrantSize`. Thus it breaks on build when adding this plugin to a 4.2 project.

Could there be a 4.2 branch for this, please?

**Comment by Kiamo2** [comment]
Just tested with 4.2 beta3 and despite some warnings about a depreceated function 'make_polygons_from_outlines()' the build succeeded!
-> I'd rather wait for the stable release of 4.2 before doing anything for 4.2.
Who knows what else they will change by then.

**Comment by Kiamo2** [comment]
Closed as a build break cannot be reproduced with 4.2 beta3 (currently latest).
