### ISSUE TITLE
Reimporting multiple maps at once with same tileset results in hundreds to thousands of errors

### ISSUE THREAD

**Issue by JSchrepp** [Kiamo2/YATI#31]
**Describe the bug**
When refocusing on Godot to let the addon reimport changes, and multiple tmx files have had changes, hundreds of thousands of errors repeat themselves in the Godot console. The easiest error message to reproduce is `This function in this node (Tile Layer 1) can only be accessed from either the main thread or a thread group. Use call_deferred() instead.` but I have seen others. It's also very easy for me generate exactly 1280 errors (not including errors from #30).

Following these errors, `Import succeeded.` is printed to the console, but opening the imported tmx file in the scene editor shows this is not the case.

**To Reproduce**
1. Import two tmx files through the addon.
2. Edit both maps without refocusing on the godot editor
3. refocus on the godot editor.

**Expected behavior**
No error messages. successful import.

**Desktop (please complete the following information):**
- OS: Windows 11
- Version 1.6.0 csharp
- Godot Version 4.1.1 .NET version
- Tiled Version 1.10.2

**Examle map (zipped)**
Same zip in #30

**Comment by Kiamo2** [comment]
I assume you don't have switched off 'Use multiple threads' in your project settings.
Please do so as recommended in the Readme.

**Comment by JSchrepp** [comment]
@Kiamo2 Thank you! This does indeed fix it. Can I make a couple recommendations to make this info easier to find?

1. If known issues are going to be in a readme, putting such a section near the top is good practice to alert people, rather than at the bottom or nestled in a bullet list
2. This seems a perfect candidate to have as an actual github issue. Even if it's not going to get fixed anytime soon, it's pretty common practice to have known issues sitting there where they can be searched, elaborated on, host discussion on the topic, etc.
