### ISSUE TITLE
Please add Object IDs to the imported nodes

### ISSUE THREAD

**Issue by LoraHart** [Kiamo2/YATI#32]
**Is your feature request related to a problem? Please describe.**

When I use custom properties of type "object" I get a field in the metadata with the integer value of the ID of the linked object. I don't think the object IDs are imported. At least, I have not found a place where the object IDs are handled in the source code of YATI (gdscript).

In the example the imported TeleporterEntry node would have an "exit" field in the metadata with the value 3. I don't see an obvious way to identify the TeleporterExit object among the imported nodes.

![Screenshot 2023-11-13 160806](https://github.com/Kiamo2/YATI/assets/23659469/d00b5c97-fac2-4404-935a-7590387786d3)

**Describe the solution you'd like**

An "id" field in the metadata would be needed in order to identify the linked node in post processing. I'm not sure if that feature should be guarded by an import option (just like the "Class" field).

**Describe alternatives you've considered**

N/A

**Additional context**
Very useful Godot plugin. Thanks!

**Comment by Kiamo2** [comment]
Maybe setting the "Add class as metadata" option is useful for you.
You could then set the class attribute to e.g. "TeleporterEntry" and after import it should show up in the metadata.
Would this be an acceptable solution for you?

**Comment by Kiamo2** [comment]
Ok, I'll implement it in a future release.

In the meantime I see two possible workarounds:
1. Change the custom property 'exit' to type string and give it the value 'TeleporterExit'.

or

2. Add to TeleporterExit a custom property of name 'object_id' and of type object and link it to itself.
This way a change of the id in Tiled should be automatically be reflected in a change of this value.

**Comment by LoraHart** [comment]
> Ok, I'll implement it in a future release.

Very good, thank you! I have "hacked" a workaround until then. In the beginning of the function handle_object (in TilemapCreator.gd) I remember the object id:

`func handle_object(obj: Dictionary, layer_node: Node, tileset: TileSet, offset: Vector2) -> void:
	var obj_id = obj.get("id", null)
...`

Further down every time the "class" metadata is set I also set the object id. For instance:

`		if _add_class_as_metadata and class_string != "":
			obj_sprite.set_meta("class", class_string)
		if obj_id != null:
			obj_sprite.set_meta("id", obj_id)
`
I'm not remotely sure if that is correct but it works for my use case for now. 

> Maybe setting the "Add class as metadata" option is useful for you.

This is an indication for me that I might have picked the right places :)

> Add to TeleporterExit a custom property of name 'object_id' and of type object and link it to itself.
> This way a change of the id in Tiled should be automatically be reflected in a change of this value.

That is very clever! This even works when you copy/paste the object. The property becomes a self reference of the new object.

**Comment by Kiamo2** [comment]
Just released v1.6.2 where I added a new option 'add_id_as_metadata' working similar like 'add_class_as_metadata'.
I choose to guard it by that option because you never know if someone might not like that.

**Comment by LoraHart** [comment]
Thank you very much! I plan to integrate the new release during this week.

**Comment by LoraHart** [comment]
Works perfectly for me. The issue can be closed as far as I'm concerned.
