### ISSUE TITLE
Add a way to set the TileSet Texture NormalMap Texture and Specular Texture

### ISSUE THREAD

**Issue by Lertsenem** [Kiamo2/YATI#34]
**Is your feature request related to a problem? Please describe.**
I'm using NormalMaps in my level in order to simply achieve some beautiful lighting effects. Unfortunately, I found no way to do that using YATI.

**Describe the solution you'd like**
It could maybe be added as a file CustomProperty of the tileset in Tiled? Or independently for each tile when using separate tiles pictures?

**Describe alternatives you've considered**
For now I need to manually modify the node generated by YATI, changing the TileSet Texture (CanvasTexture) and manually adding the TileMap Texture parameter. Unfortunately I need to redo this each time I make a change in my Tiled level.

**Additional context**
Thanks for making YATI, that's a brilliant plugin that I now can't live without. :]

**Comment by Kiamo2** [comment]
The list of Godot specific properties is already quite long so I refrained from materials altogether.
The proposed solution for that case is to save the Godot material settings to a material file (usually a .tres file) and add a Tiled custom property 'material' of type file and set its value to that material file.
The importer loads the material file just as if you would load it manually.
Would that be a viable option for you?

**Comment by Kiamo2** [comment]
No further feedback.
-> Issue is considered resolved.

**Comment by Lertsenem** [comment]
Sorry, I missed your first answer!

Thanks, I did not realize this was the way to go, and it indeed works for me! Maybe it could be worth adding some text about it in the ref doc? Anyway, thanks a lot for your help!

**Comment by Kiamo2** [comment]
Following your proposal I've added some text to the ref doc.

**Comment by Lertsenem** [comment]
Wow, you're so fast! Thanks a lot!

Le 13 décembre 2023 12:20:34 GMT+01:00, Roland ***@***.***> a écrit :
