### ISSUE TITLE
Maps in projects exported on macOS are lacking collision data

### ISSUE THREAD

**Issue by Avelion114** [Kiamo2/YATI#35]
**Describe the bug**
Maps imported with YATI lack all collision data when exported to macOS using the macOS template in Godot 4.2

**To Reproduce**
Import a map from Tiled to Godot 4.2 with YATI
On a Mac running 13.5 load the project (we are working via multiple machines using GitHub with macOS and Windows)
Project->Export
Select the macOS export template
Fill out necessary info for project
Export Project

**Expected behavior**
The project runs in a similar fashion to Windows export with maps having all collision and visual data

**Screenshots**

**Desktop (please complete the following information):**
We are developing on both Windows 10 and macOS 13.5 
Tiled maps are being developed and imported on Windows 10
macOS export is being done on macOS 13.5

 - OS: macOS
 - Version: 10.13.5
 - Godot Version 4.2
 - Tiled Version 10.1.2

**Additional context**
Just looking for any feedback on possible resolution of things we may be doing incorrectly. If there are any external resource file extensions that need to be included in the Resource filters on the export options please let us know. Everything runs fantastic on windows. All animations and tiles are preset on Mac, the only thing lacking is the collision layer. 
Thanks!

**Comment by Kiamo2** [comment]
I'm afraid I can't help here.
Firstly, I don't have a Mac and secondly, I don't really believe that the export problem has anything to do with YATI.

I would rather suspect some issue with the Mac export template.
Does it work with Godot 4.1?

Any Mac users here who have an idea?

**Comment by Avelion114** [comment]
That's unfortunate but thank you anyways. The reason I suspected YATI is I recreated a map directly in godot as opposed to importing and things worked as they should. I will continue to test and if I find a related issue I will let you know.

**Comment by Kiamo2** [comment]
Yeah, please keep me informed in any case.
I have thought (without Mac) on an abstract level about what it could be, but so far no idea.
And also not yet any relevant result on googling for known Godot4 Mac export issues.
Strange...

**Comment by Avelion114** [comment]
I discovered a solution
Again I'm not sure if this has to do with YATI or Godot
But after importing the maps we did make instanced scenes from the TMX files so we could edit things in engine. 
I'm wondering if the TileSet collision data isn't properly transferred in that process.

By duplicating all the instanced tilemaps (ones in yellow) and moving them to a new scene, all collisions work on the Mac export.

**Comment by Kiamo2** [comment]
Even more strange.
Did you perform absolutely the same steps under Windows and under MacOS?

Anyway I'm inclined to blame it on Godot as the YATI code itself has no OS specifics.

**Comment by Avelion114** [comment]
Yes we did. In fact switching the tileset on the imported tilemap did not work either. They apparently cannot be instanced. 

Anyways I appreciate your insight!

**Comment by Kiamo2** [comment]
Any new findings here?
Really don't know what to do about that.
