### ISSUE TITLE
add support to not import a tilemap layer with a custom property "noImport" with property value of true

### ISSUE THREAD

**Issue by erniel** [Kiamo2/YATI#4]

**Comment by Kiamo2** [comment]
As this is an importer, why "export"?

**Comment by Kiamo2** [comment]
Ok.
Is there a reason for both option + property? i.e. wouldn't it be sufficient to only have the property?

**Comment by Kiamo2** [comment]
Ok, fine.
BTW one way collision already should be supported by the relevant properties (see reference document).

**Comment by erniel** [comment]
i mean one way collision for tilemaps. it tried and its only available for collision object.

**Comment by Kiamo2** [comment]
Where can I find one way collsion _for tilemaps_ in Godot 4?
I don't see anything of that sort.

**Comment by Kiamo2** [comment]
v1.2: Skipping a layer (any layer not only tilemap layers) by adding a custom bool property 'no_import' and set it to true is now possible. (I've use snake case to be consistent to all property naming)
