### ISSUE TITLE
Support TileMapLayer nodes from Godot 4.3

### ISSUE THREAD

**Issue by dogboydog** [Kiamo2/YATI#44]
**Is your feature request related to a problem? Please describe.**
Starting in Godot 4.3 dev 6, the TileMap node is marked as deprecated in favor of TileMapLayer, which they say is a very similar API but has some improvements over TileMap
https://godotengine.org/article/dev-snapshot-godot-4-3-dev-6/

**Describe the solution you'd like**
If the engine is 4.3 dev 6 or newer,  use the TileMapLayer API rather than TileMap 

**Describe alternatives you've considered**
Accepting deprecation warnings when compiling C# or suppressing them in these files. It's an interim solution. 

**Additional context**
n/a

**Comment by Kiamo2** [comment]
I (of course) will look into this but not before version 4.3 stable is released.

**Comment by feendrache** [comment]
Hey there, 
since 4.3 is stable... do you have a timeframe for this?

**Comment by Kiamo2** [comment]
Next few days.
I'm planning a release (v2.0) which will not be compatible to Godot 4.2.x or older.
(Originally I had hoped that this would not be necessary, but the code would then become quite confusing.)

**Comment by feendrache** [comment]
oh "next few days" you're my hero :) thank you

**Comment by dogboydog** [comment]
> Next few days. I'm planning a release (v2.0) which will not be compatible to Godot 4.2.x or older. (Originally I had hoped that this would not be necessary, but the code would then become quite confusing.)

I wonder if it could be simpler if you used a type alias that was behind an #if 

```csharp 
#if GODOT4_2_OR_GREATER
using YATIMap = TileMapLayer;
#else 
using YATIMap = TileMap; 
#endif

// ... 
map = new YATIMap(); 
```
Assuming the API / properties for the TileMapLayer are mostly the same

**Comment by Kiamo2** [comment]
@dogboydog: Not sure if this assumption (API / properties same) is true.
And not sure if GDScript and C# both have such preprocessor if-else-endifs.
+ there's more - the (old) TileMap additionally had "Layers". By the importer's option "use _tilemap_layers" it was possible to make use of those sublayers. These sublayers had the drawback that they had no offset.
With the new TileMapLayer I think I can get rid of the importer option and all subsequent code gets way simpler which I like :-)
