### ISSUE TITLE
Error when enabling

### ISSUE THREAD

**Issue by Josephur** [Kiamo2/YATI#45]
**Describe the bug**
Made a new project in Godot (mono with c# support) v4.2.2
Added  default empty 2d scene, and set it as default and ran the project once.
Closed Godot.
Unzip the addons folder from YATI zip file to my project folder.
Go to Project, Settings, Plugins and check the box to enable YATI.

Get the error: "Unable to load addon script from path: 'res://addons/YATI/TiledImport.cs'. This might be due to a code error in the script.  Disabling the addon at 'res://addons/YATI/plugin.cfg' to prevent further errors."

**Expected behavior**
YATI gets enabled and I can learn how to use it.

**Screenshots**
![image](https://github.com/Kiamo2/YATI/assets/6666442/c99cdcc4-cf7a-4713-ae85-55bd2bea1049)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 23H2 22631.3527
 - Godot Version 4.2.2
 - Tiled Version 1.10.2

**Comment by Josephur** [comment]
The GDscript version works fine, the C# will not enable for me.  I even clicked the edit icon to make sure the CSharp one was set to C# not GDScript (it defaulted to GDScript for me).

**Comment by Kiamo2** [comment]
The problem with the C# version is that an initial C# build of the whole project must be run.
Please create a basic script (nearly emtpy) in your project and run it by pressing the start button.
(There should be a short message popping up about doing an C# build)
After that hopefully plugin enabling should succeed.

**Comment by Josephur** [comment]
I tried just that, make a Dummy.cs file with the empty Godot C# script template, compiled it, ran the project, closed the project, extracted the plugin, go to enable the plugin it says it's GDScript even though I'm unzipping the C# one, so I correct that, click to enable and get the same exact error.

**Comment by Josephur** [comment]
Ohhhh, one second I just got it!  The key was to mark it as C#, and hit Update, but do not check to enable it, re-compile the project again, then after its ran it will enable.... wow.

**Comment by Josephur** [comment]
Closing the issue as it's a known issue, you just may need to change the Script type to C#, save that setting, compile project, then go in and Enable the plugin.
