### ISSUE TITLE
Custom Properties defined on object tile definitions do not propogate. 

### ISSUE THREAD

**Issue by MisterrNibble** [Kiamo2/YATI#49]
**Describe the bug**
Custom Properties defined on object tile definitions do not propagate. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a tile project
2. Create a tileset with at least one tile
3. On the tileset create a custom properties on the tiles (e.g. "godot_script" -> "../scripts/lights.gd")
4. On the tilemap create an object layer
5. Place tiles in a map
6. Load map into Godot4

Or succinctly: Property in the tsx, but not in the tmx on object layers.

**Expected behavior**
Custom properties should propogate through from the tileset, so that a tile with can have a script (or any other custom) defined in the tileset.  Otherwise each instance of the tile needs to have the property set in the map editor.

**Screenshots**

**Additional context**
I had a (poor) go fixing it myself, the function handle_object in TilemapCreator can be made to reference back to the custom data layer of the tileset, and while elegant enough for my own needs it seemed a bit hacky; theres possibly a better way.  Awesome tool otherwise :)

**Comment by Kiamo2** [comment]
Ok, haven't come across this use case yet.

**Comment by MisterrNibble** [comment]
The way I came across it was wanting to add an object layer with tile based objects representing lighting placement. In the tiles map editor I can assign a godot_script custom script to each tile-based object on the object layer, but it's so laborious.  I can add the custom script to the tileset, but the importer doesn't look at the "default" properties in the tileset when creating the sprite, which is a shame because the custom properties are imported to the tileset in godot as custom data layers, they just never get preference when handling the properties in the object creator.On 08/07/2024, 19:26 Roland ***@***.***> wrote:

   
  Ok, haven't come across this use case yet.

**Comment by Kiamo2** [comment]
You could help me a bit by providing a little use case example i.e. a small Tiled project + manipulated Godot result illustrating how it should look.

**Comment by Kiamo2** [comment]
Should be now fixed with release 1.6.8 / 2.0.0
