### ISSUE TITLE
Runtime package breaks when project is exported

### ISSUE THREAD

**Issue by CurryOnRice** [Kiamo2/YATI#51]
**Describe the bug**
First of all, thank you very much for having made this amazing plugin!
I believe the runtime package doesn't work after exporting the project. This is because Godot will not import the .tmx files, but will import the .png files that are used, which messes up the relative paths.
For example, my floor spritesheet ended up being exported into this directory:
![image](https://github.com/user-attachments/assets/0382c1ae-97cd-47c5-be71-75c67f51b35a)
Whereas the .tmx don't get imported, so they stay in their original directory:
![image](https://github.com/user-attachments/assets/c77a34b4-9d8d-4544-97f7-675043e0dedc)
Which results in this error:
![image](https://github.com/user-attachments/assets/b4f4f8a8-4761-44c2-97d8-4119a8eb8ba7)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Godot Version: 4.2
 - Tiled Version: 1.6.7

**Comment by Kiamo2** [comment]
The runtime package was created at the special request of some people who explained that they would benefit from it.
I have never used it myself and have no experience with exporting.
So currently I not able to help here - sorry.
I also can't really judge whether the runtime package is suitable for this use case at all.
