### ISSUE TITLE
Support Custom Extension to Import

### ISSUE THREAD

**Issue by JSchrepp** [Kiamo2/YATI#55]
**Is your feature request related to a problem? Please describe.**
When importing many maps, there is bound to be reuse of game-specific component structure that is attached to/alongside the TileMapLayer scenes at development time. Management components may get attached to whole maps. Specific cells based on tile or metadata contents may always want a specific component placed on top of them. One can imagine a scene structure as below being deterministically generated for every Tiled map imported

```
LevelScene
|-- TileMapLayer (this is what YATI currently imports)
|-- SomeManagerManager
|-- LoadTriggers
|   |-- LoadNorthChunkTriggerArea2D
|   |-- LoadEastChunkTriggerArea2D
|   |-- LoadSouthChunkTriggerArea2D
|   |-- LoadWestChunkTriggerArea2D
|-- TileEmitters
|   |-- 4_3_Emitter
|   |-- 8_34_Emitter
```

Doing this by hand, especially when using Tiled's "world" system to generate many smaller maps, may result in many hours of dev tedium for manually attaching every component in the exact same way every time.

**Describe the solution you'd like**
A mechanism built into YATI where users can write code which accepts the current scene built by YATI and outputs an arbitrary new scene. YATI would be able to detect this extra step and call the code appropriately.

**Describe alternatives you've considered**
Modifying YATI in my own project. Godot plugins are just imported source code, and so any user could modify YATI to do this in the way their development cycle needs. However, such modifications make pulling in mainline updates and fixes more complex. Ideally my own code would be separate from YATI's entirely.

**Additional context**
N/A

**Comment by Kiamo2** [comment]
I'm afk til Sunday, will think then about this request.

**Comment by Kiamo2** [comment]
What about the (already existing) post processing option?

**Comment by JSchrepp** [comment]
I was struggling to find that but it looks like exactly the sort of thing i'm talking about. Thank you!
