### ISSUE TITLE
1.2.0 breaking change out of box creating tileset (GDScript)

### ISSUE THREAD

**Issue by JSchrepp** [Kiamo2/YATI#6]
**Describe the bug**
When using isometric tiles that are a different size from the grid tile (e.g. double height tiles for trees as pictured in example below)
![image](https://user-images.githubusercontent.com/15899212/228700883-d84c4858-3657-48b3-95ad-592024ad1653.png)
version 1.1.2 would import the tiles with expected alignment (matching how Tiled interprets them when painting to a map)
![image](https://user-images.githubusercontent.com/15899212/228701092-01924cc6-830c-405e-8fd5-bbf7905c49b5.png)
In version 1.2.0 (and onwards) tiled imports the tileset assuming the boundary for where to place the tile is centered
![image](https://user-images.githubusercontent.com/15899212/228701257-1dc4402f-e583-4c6a-981e-301b4620c7f3.png)
This results in tiles being painted half a tile lower than expected as depicted below
![image](https://user-images.githubusercontent.com/15899212/228701396-bcc856bd-80af-41bd-b574-3ef768b6a68a.png)

Additionally, their collision physics are now completely distorted, see below for comparison:
![image](https://user-images.githubusercontent.com/15899212/228701749-8fa93f14-7749-4c21-816d-644569d152f3.png)
![image](https://user-images.githubusercontent.com/15899212/228701597-e8470d8f-6c79-4807-b61d-40df1e97a019.png)

**To Reproduce**
1. Use the provided sample map (no extra configuration used)
2. Import using version 1.2.0 or later

**Expected behavior**
Tileset should import as expected, like it used to.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.2.0
 - Godot Version 4.0.1
 - Tiled Version 1.10.0

**Example map (zipped)**
[tempfarm.zip](https://github.com/Kiamo2/YATI/files/11106789/tempfarm.zip)

**Additional context**

**Comment by JSchrepp** [comment]
I notice a couple places is TilesetCreator.gd where the condition `if _tileset_orientation == "orthogonal"` was added that seem to transform some things about texture mapping. Removing those branches *almost* reverts behavior. The first tile still exhibits the shift but the rest are realigned. Perhaps this helps you narrow down the culprit.
![image](https://user-images.githubusercontent.com/15899212/228706515-51bfe99e-9216-4a15-82c4-9001007a4fcd.png)

**Comment by Kiamo2** [comment]
Hi, I'm sorry that you've just stumbled upon my current construction site (isometric tiles) and that I seem to have temporarily made things worse here as well.
Actually I am in the process of completely reworking isometric so that it is correct for all displacements and height/width ratios etc. including the collision polygons, whose .tmx/.tsx geometry data (in the case of isometric) the devil has seen.
Could possibly take more than a few hours, as I really want to be thorough this time.
Thank you for your example, that will help me a lot.

**Comment by JSchrepp** [comment]
> Interestingly your .tsx is NOT set to 'isometric'. That's one more combination (isometric map, non-isometric tileset) to be handled. (And that's most probably the reason why in 1.1.2 it works but no longer in 1.2.1)

Interesting! I must have missed this property as it wasn't available on creation in Tiled like it is on maps. In fact, setting the tileset back to isometric with appropriate grid dimensions creates the exact collision-box distortion in the issue description.

When making this adjustment on my end to label the tileset as it should be, I notice my collision import is as desired, but the centering of the tile on the grid still exists, rather than snapping to the bottom as it used to. Updated tileset below works with tiled as expected but is still offset by half a tile vertically in godot.
[testset.zip](https://github.com/Kiamo2/YATI/files/11112241/testset.zip)

**Comment by Kiamo2** [comment]
Concerning "... to label the tileset as it should be". I'm not sure that this is a strict 'should be'. I assume that it's depending weather one likes to have the automatically skewed rectangles or not. The overall map (in Tiled) seems to work both ways so I have to ensure that both ways are importable and have the absolutely same result.
The offset by half a tile is another animal having not exactly to do with the tileset being isometric or orthogonal.
It probably was introduced by the condition ` if _map_orientation == "orthogonal" ` in TilemapCreator.gd as well as that one mentioned by you.
I will remove that and find another way to correct that isometric test design of mine which is then off :-)
The challenge is: All contingencies must work.
Please give me some time...

**Comment by Kiamo2** [comment]
Hi, just have released v1.2.2 and hope that the issues discussed here are solved.
Thanks for all your input.

**Comment by JSchrepp** [comment]
This solves most of the issue! Isometric tiles are once again properly aligned in the imported tileset. However, collision information is not properly transferred, as depicted below in the TileSet window in Godot. The reproduction assets I sent you should already have this collision info in the .tsx file, so I imagine you should be able to reproduce this.
![image](https://user-images.githubusercontent.com/15899212/229313931-199c24bd-c88b-4b55-8212-581fe305e9de.png)

**Comment by Kiamo2** [comment]
Ooops! I've typed in one single sign wrong when translating from C# to GDScript (I'm developing in C#).
And in the tests I must have missed exactly that, perhaps only checked the orthogonal version.
I'm very sorry for that, that really should not happen!!
Fixed in upcoming v1.2.3.
As I'm not yet sure if I also have to fix s.th. for the other issue #7 and should that be delayed you can fix it simply by changing line 376 in (TilesetCreator.gd) from
`object_base_coords.y += _grid_size.y / 2.0`
to
`object_base_coords.y -= _grid_size.y / 2.0`

**Comment by Kiamo2** [comment]
I'd like to close the issue. Ok?

**Comment by JSchrepp** [comment]
I haven't had a chance to test this yet but it seems like you've identified and solved the issue. I can reopen if it doesn't work for me.
