### ISSUE TITLE
Alter - unknow file format messagebox

### ISSUE THREAD

**Issue by andreas-volz** [Kiamo2/YATI#65]
**Describe the bug**
no real error as everything seems to work, only this box

**To Reproduce**
1. Start project
2. Run project
3. one second Alert messagebox and then disapear
4. 

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/82ac3fed-63e1-4f68-9f82-a607d7b3c813)

**Desktop (please complete the following information):**
OS: Linux
Godot Version 4.3
Tiled Version 1.8.0

**Additional context**

**Comment by Kiamo2** [comment]
Sorry, I can't reproduce this alert no matter what I try.
Maybe it's something OS specific, I'm working on Windows, don't have Linux.
-> Can't help you here.

**Comment by Kiamo2** [comment]
What about this now?
