### ISSUE TITLE
Tile collision rectangle not setting properly on its physics layer

### ISSUE THREAD

**Issue by erniel** [Kiamo2/YATI#7]
**Describe the bug**
i have one tileset and the collision layers are separated in two. ground and bridge.
![image](https://user-images.githubusercontent.com/20150952/229329262-b920e15c-c80d-4bb9-b0a4-7797964f0daf.png)

i added a custom property physics layer with value 0 for ground, and physics layer 1 for bridge on thier each collision rectangle.
![image](https://user-images.githubusercontent.com/20150952/229329367-2c848567-d55b-47d6-9e35-d937fb755a28.png)
![image](https://user-images.githubusercontent.com/20150952/229329368-ae887154-a837-48c1-9ea0-4550f610ec88.png)

when imported all collision are just set to physics layer 0
![image](https://user-images.githubusercontent.com/20150952/229329424-37550033-9185-4f0b-a4e4-7a79a5cfbb70.png)
![image](https://user-images.githubusercontent.com/20150952/229329426-067aaf14-3837-49b8-be42-87997b119cd1.png)

im not sure if its a bug or not implemented yet. but ive seen on the document on base tile there's a property physics_layer with int type. and these are the desired result when imported.

![image](https://user-images.githubusercontent.com/20150952/229329548-5f564aa2-e445-4d53-9ec9-68956a839eac.png)
![image](https://user-images.githubusercontent.com/20150952/229329549-c6822821-11a7-4784-8724-04ba1e2c3c4e.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - YATI Version 1.2
 - Godot Version 4.0 stable
 - Tiled Version 1.10

**Comment by Kiamo2** [comment]
Hi, this was indeed a bug and should be fixed now in v1.2.3.

BTW I see that you gave collision_layer_0 a value 'collision_layer=1,3'. That will not work. The value should be only '1,3'.
(This also applies for most other properties here).
And a value of 0 like in collision_layer_1 will be useless, as layer numbers are starting with 1.
