### ISSUE TITLE
Import issues when changing map structure

### ISSUE THREAD

**Issue by tavurth** [Kiamo2/YATI#8]
**Describe the bug**
When adding a new layer or changing a collision polygon, the map fails to import.
Godot must be restarted to see changes.

**To Reproduce**
1. Load a tilemap
2. Change a collision shape in Tiled
3. The level will not update in godot
4. Even if you try to force update it

**Expected behavior**
That the file should have it's cache cleared and re-imported

**Screenshots**
...

**Desktop (please complete the following information):**
 - OS: OSX
 - Version Latest
 - Godot Version Godot 4.02
 - Tiled Version 1.10.1

**Comment by Kiamo2** [comment]
Sorry for the late answer, I had a week off from the web.
What you are describing is probably a Godot refreshing issue. Please see the discussion [here](https://discord.com/channels/524610627545595904/1075689054101852200) (around april 9th/10th).
On the importer's (code) side there's nothing that could be done I'm afraid.
But as I'm not on OSX (and have no access to an OSX machine) I'm not quite sure. Also not sure if the in the discussion mentioned "tricks" with switching to another application or minimizing and maximizing the Godot window work in OSX.

**Comment by tavurth** [comment]
Ok that makes sense, I'll close this one then 👍
